# Generated by Django 3.2.9 on 2021-11-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_blogpost_reposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='reposts',
        ),
    ]
